# Generated by Django 2.0.7 on 2019-03-24 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Store')),
            ],
            options={
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='BillInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Friendly ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Date expired')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Taxes')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Paid Value')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='warehouse.BillCategory', verbose_name='Bill')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='PaymentMethod')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Invoice',
                'verbose_name_plural': '1. Bill Invoice',
                'ordering': ['-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64, verbose_name='Occupation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Balance')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.Store')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': '5. Occupations',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Friendly ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Date expired')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Taxes')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Paid Value')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('category', models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ'), ('6', 'ΔΩΡΟ')], default='1', max_length=1)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='PaymentMethod')),
            ],
            options={
                'verbose_name': 'Εντολή Πληρωμής',
                'verbose_name_plural': '2. Μισθόδοσία',
                'ordering': ['is_paid', '-date_expired'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
                ('date_started', models.DateField(default=django.utils.timezone.now, verbose_name='Date started')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Balance')),
                ('vacation_days', models.IntegerField(default=0, verbose_name='Remaining Vacation Days')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.Occupation', verbose_name='Occupation')),
            ],
            options={
                'verbose_name': 'Υπάλληλος',
                'verbose_name_plural': '6. Υπάλληλος',
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_invoices', to='warehouse.Person', verbose_name='Υπάλληλος'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
