# Generated by Django 2.0.7 on 2019-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='store',
            field=models.ManyToManyField(blank=True, null=True, to='site_settings.Store'),
        ),
    ]
