# Generated by Django 2.0.7 on 2019-04-12 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190411_1537'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_settings', '0006_auto_20190402_1611'),
        ('warehouse', '0002_auto_20190326_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Friendly ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_expired', models.DateField(default=django.utils.timezone.now, verbose_name='Date expired')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Paid Value')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('clean_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('taxes_modifier', models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('order_type', models.CharField(choices=[('1', 'Τιμολόγιο - Δελτίο Αποστολής'), ('2', 'Τιμολόγιο'), ('3', 'Δελτίο Απόστολης'), ('4', 'Εισαγωγή Αποθήκης'), ('5', 'Εξαγωγή Αποθήκης')], default=1, max_length=1)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='PaymentMethod')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_orders', to='catalogue.Vendor')),
            ],
            options={
                'verbose_name_plural': '1. Warehouse Invoice',
                'ordering': ['-date_expired'],
            },
        ),
    ]
