# Generated by Django 2.0.7 on 2019-04-14 05:39

from django.db import migrations, models
import django.db.models.deletion
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190411_1537'),
        ('warehouse', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=warehouse.models.upload_image, validators=[warehouse.models.validate_file])),
                ('is_first', models.BooleanField(default=True)),
                ('order_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Τελευταίας Επεξεργασίας')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Ποσότητα')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Άρχικη Αξία')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ποσοστό Έκτωσης')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Αξία')),
                ('unit', models.CharField(choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Κιβώτια')], default='1', max_length=1)),
                ('total_clean_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_final_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='warehouse.Invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_products', to='catalogue.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
