# Generated by Django 2.0.7 on 2019-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190414_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
