# Generated by Django 2.0.7 on 2019-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190414_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorderitem',
            name='sku',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
