# Generated by Django 2.0.7 on 2019-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_invoiceorderitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorderitem',
            name='discount_value',
            field=models.IntegerField(default=0, verbose_name='Discount %'),
        ),
    ]
