# Generated by Django 2.0.7 on 2019-04-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20190414_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
