# Generated by Django 2.0 on 2019-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20190416_1419'),
        ('warehouse', '0010_auto_20190416_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paycheck',
            field=models.ManyToManyField(to='catalogue.VendorPaycheck'),
        ),
    ]
