# Generated by Django 2.0 on 2019-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Off the record Manual Balance', max_digits=20),
        ),
    ]
