# Generated by Django 2.0.7 on 2019-03-29 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0011_auto_20190324_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('site_settings', '0003_auto_20190326_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Postal')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
                ('need_invoice', models.BooleanField(default=False)),
                ('is_retail', models.BooleanField(default=True)),
                ('is_eshop', models.BooleanField(default=True)),
                ('vat', models.CharField(blank=True, max_length=9, verbose_name='ΑΦΜ')),
                ('vat_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_detail', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Friendly ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_expired', models.DateField(default=datetime.datetime(2019, 3, 29, 8, 24, 5, 451149), verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Taxes')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Paid Value')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('1', 'Νέα Παραγγελία'), ('2', 'Σε επεξεργασία'), ('3', 'Έτοιμη προς αποστολή'), ('4', 'Απεστάλη'), ('5', 'Επιστράφηκε'), ('6', 'Ακυρώθηκε'), ('7', 'Εισπράκτηκε'), ('8', 'Ολοκληρώθηκε')], default='1', max_length=1)),
                ('order_type', models.CharField(choices=[('r', 'Λιανική Πώληση'), ('e', 'Πώληση Eshop'), ('b', 'Παραστατικό Επιστροφής'), ('c', 'Ακυρωμένη Παραγγελία'), ('wa', 'Παραστατικό Εισαγωγής'), ('wr', 'Παραστατικό Εξαγωγής')], default='r', max_length=1, verbose_name='Order Type')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Cost')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Μεταφορικά')),
                ('payment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Κόστος Αντικαταβολής')),
                ('day_sent', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αποστολής')),
                ('eshop_session_id', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_of_sale.BillingAddress')),
                ('cart_related', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Cart')),
                ('order_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sale.Order')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.PaymentMethod', verbose_name='Payment Type')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Shipping', verbose_name='Τρόπος Μεταφοράς')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': '1. Orders',
                'ordering': ['-date_expired'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Qty')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount %')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('attribute', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=0, default=0, help_text='qty*final_value', max_digits=20)),
                ('total_cost_value', models.DecimalField(decimal_places=0, default=0, help_text='qty*cost', max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='point_of_sale.Order')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items', to='catalogue.Product')),
            ],
            options={
                'verbose_name_plural': '2. Προϊόντα Πωληθέντα',
                'ordering': ['-order__timestamp'],
            },
            managers=[
                ('broswer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='Postal')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('cellphone', models.CharField(blank=True, max_length=10, verbose_name='Cell Phone')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='point_of_sale.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Costumer'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='retailorderitem',
            unique_together={('title', 'order')},
        ),
    ]
