# Generated by Django 2.0.7 on 2019-04-18 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 18, 11, 57, 7, 648551, tzinfo=utc), verbose_name='Date'),
        ),
    ]
