# Generated by Django 2.0 on 2019-03-29 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190329_1922'),
        ('point_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Qty')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Value')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Discount %')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Final Value')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_find', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('attribute', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=0, default=0, help_text='qty*final_value', max_digits=20)),
                ('total_cost_value', models.DecimalField(decimal_places=0, default=0, help_text='qty*cost', max_digits=20)),
            ],
            options={
                'verbose_name_plural': '2. Προϊόντα Πωληθέντα',
                'ordering': ['-order__timestamp'],
            },
            managers=[
                ('broswer', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='retailorderitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='retailorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='retailorderitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 19, 21, 15, 257350), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='RetailOrderItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='point_of_sale.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items', to='catalogue.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('title', 'order')},
        ),
    ]
