# Generated by Django 2.0.7 on 2019-04-19 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_auto_20190418_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.AddField(
            model_name='order',
            name='taxes_modifier',
            field=models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 12, 32, 7, 730382, tzinfo=utc), verbose_name='Date'),
        ),
    ]
