# Generated by Django 2.0.7 on 2019-04-01 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0003_auto_20190330_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 1, 17, 19, 52, 746554), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderitemattribute',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='point_of_sale.OrderItem'),
        ),
    ]
