# Generated by Django 2.0.7 on 2019-04-02 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20190401_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 15, 14, 42, 715942), verbose_name='Date'),
        ),
    ]
