# Generated by Django 2.0 on 2019-04-20 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_auto_20190420_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 20, 12, 12, 24, 745886, tzinfo=utc), verbose_name='Date'),
        ),
    ]
