# Generated by Django 2.0.7 on 2019-04-23 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0005_auto_20190420_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 23, 11, 45, 7, 536058, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_items', to='catalogue.Product'),
        ),
    ]
