# Generated by Django 2.0.7 on 2019-04-23 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190418_1457'),
        ('point_of_sale', '0006_auto_20190423_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='attr_class',
        ),
        migrations.RemoveField(
            model_name='orderitemattribute',
            name='title',
        ),
        migrations.AddField(
            model_name='orderitemattribute',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Attribute'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 23, 18, 41, 22, 189912, tzinfo=utc), verbose_name='Date'),
        ),
    ]
