# Generated by Django 2.0.7 on 2019-04-02 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_auto_20190402_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 15, 42, 42, 505285), verbose_name='Date'),
        ),
    ]
