# Generated by Django 2.0.7 on 2019-04-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_auto_20190402_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 16, 9, 26, 549197), verbose_name='Date'),
        ),
    ]
