# Generated by Django 2.0.7 on 2019-04-06 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0009_auto_20190402_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 6, 14, 28, 15, 633397), verbose_name='Date'),
        ),
    ]
