# Generated by Django 2.0.7 on 2019-04-09 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20190402_1611'),
        ('point_of_sale', '0010_auto_20190406_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
                ('cellphone', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField()),
                ('order_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=50)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='site_settings.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 16, 27, 23, 168978), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='orderprofile',
            name='order_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_profiles', to='point_of_sale.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderprofile',
            unique_together={('order_related', 'order_type')},
        ),
    ]
