# Generated by Django 2.0.7 on 2019-04-10 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0011_auto_20190409_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 10, 7, 46, 53, 112319), verbose_name='Date'),
        ),
    ]
