# Generated by Django 2.0.7 on 2019-04-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0012_auto_20190410_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 11, 15, 24, 40, 462439), verbose_name='Date'),
        ),
    ]
