# Generated by Django 2.0.7 on 2019-04-14 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0017_auto_20190414_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 8, 41, 6, 939788), verbose_name='Date'),
        ),
    ]
