# Generated by Django 2.0.7 on 2019-04-14 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0018_auto_20190414_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 10, 13, 2, 886188), verbose_name='Date'),
        ),
    ]
