# Generated by Django 2.0.7 on 2019-04-14 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0019_auto_20190414_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 10, 37, 20, 113839), verbose_name='Date'),
        ),
    ]
