# Generated by Django 2.0.7 on 2019-04-14 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0020_auto_20190414_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 10, 51, 49, 635537), verbose_name='Date'),
        ),
    ]
