# Generated by Django 2.0.7 on 2019-04-14 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0021_auto_20190414_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 15, 42, 7, 917594), verbose_name='Date'),
        ),
    ]
