# Generated by Django 2.0 on 2019-04-16 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0022_auto_20190414_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 14, 19, 7, 466218), verbose_name='Date'),
        ),
    ]
