# Generated by Django 2.0 on 2019-04-16 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0023_auto_20190416_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 19, 7, 8, 447149), verbose_name='Date'),
        ),
    ]
