# Generated by Django 2.0 on 2019-04-17 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0024_auto_20190416_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 14, 0, 53, 580365), verbose_name='Date'),
        ),
    ]
