# Generated by Django 2.0.7 on 2019-04-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0025_auto_20190417_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 16, 22, 11, 484351), verbose_name='Date'),
        ),
    ]
