# Generated by Django 2.0 on 2019-04-17 15:20

import catalogue.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ποσότητα')),
                ('order_discount', models.IntegerField(blank=True, default=0, null=True, verbose_name="'Εκπτωση Τιμολογίου σε %")),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Τιμή Αγοράς')),
            ],
            options={
                'verbose_name_plural': 'Attribute',
                'ordering': ['title'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('have_transcations', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Attribute Class Title',
            },
        ),
        migrations.CreateModel(
            name='AttributeProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.AttributeClass')),
            ],
            options={
                'verbose_name_plural': 'Product Attribute Class',
            },
        ),
        migrations.CreateModel(
            name='AttributeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ordering_by', models.IntegerField(default=0, help_text='Bigger is first')),
                ('attri_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_values', to='catalogue.AttributeClass')),
            ],
            options={
                'verbose_name_plural': 'Attribute Title',
                'ordering': ['-ordering_by', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ενεργοποίηση')),
                ('title', models.CharField(max_length=120, verbose_name='Ονομασία Brand')),
                ('image', models.ImageField(blank=True, upload_to='brands/', validators=[catalogue.validators.validate_file], verbose_name='Εικόνα')),
                ('order_by', models.IntegerField(default=1, verbose_name='Σειρά Προτεριότητας')),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(default=240)),
                ('height', models.IntegerField(default=240)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Brands',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, help_text='610*410', null=True, upload_to=catalogue.validators.category_site_directory_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=1)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('show_on_menu', models.BooleanField(default=False, verbose_name='Active on Navbar')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.Category')),
            ],
            options={
                'verbose_name_plural': '3. Κατηγορίες Site',
                'ordering': ['-order'],
            },
            managers=[
                ('browse', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('custom_ordering', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('custom_ordering', models.IntegerField(default=0, help_text='Bigger is better', verbose_name='Ordering')),
                ('char_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_values', to='catalogue.Characteristics')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-custom_ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('gift_message', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('custom_ordering', models.IntegerField(default=1)),
                ('is_offer', models.BooleanField(default=False, verbose_name='Is Offer')),
                ('featured_product', models.BooleanField(default=False)),
                ('order_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order oode')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price Buy')),
                ('order_discount', models.IntegerField(default=0, verbose_name="'Discount on Order")),
                ('qty_measure', models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Pieces per Pack')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qty')),
                ('qty_add', models.DecimalField(decimal_places=2, default=0, help_text='System use it only if warehouse transations', max_digits=10, verbose_name='Qty Add')),
                ('qty_remove', models.DecimalField(decimal_places=2, default=0, help_text='System use it only if warehouse transations', max_digits=10, verbose_name='Qty Remove')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('measure_unit', models.CharField(blank=True, choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Κιβώτια')], default='1', max_length=1, null=True, verbose_name='Measute unit')),
                ('safe_stock', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Stock Limit')),
                ('sku', models.CharField(blank=True, max_length=150, null=True)),
                ('site_text', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='First Price')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Discount')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Brand', verbose_name='Brand Name')),
            ],
            options={
                'verbose_name_plural': '1. Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalogue.Product')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Characteristics')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.CharacteristicsValue')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('is_service', models.BooleanField(default=False, verbose_name='Is service')),
                ('have_transcations', models.BooleanField(default=True, verbose_name='Will use transcations?')),
                ('have_attribute', models.BooleanField(default=False, verbose_name='Have attributes?')),
            ],
            options={
                'verbose_name': 'Product Class',
                'verbose_name_plural': 'Product Classes',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(blank=True, help_text='Θα δημιουργηθεί αυτόματα εάν δεν συμπληρωθεί', max_length=200, null=True)),
                ('title', models.CharField(blank=True, help_text='Θα δημιουργηθεί αυτόματα εάν δεν συμπληρωθεί', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Picture')),
                ('is_back', models.BooleanField(default=False, verbose_name='Δεύτερη Εικόνα')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.Product')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=70, unique=True, verbose_name="'Title")),
                ('vat', models.CharField(blank=True, max_length=9, null=True, verbose_name='VAT')),
                ('vat_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vat City')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cellphone')),
                ('phone1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site', models.URLField(blank=True, max_length=40, null=True, verbose_name='Site')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='City')),
                ('zipcode', models.CharField(blank=True, max_length=40, null=True, verbose_name='Zipcode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detaiks')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('taxes_modifier', models.CharField(choices=[('1', 13), ('2', 23), ('3', 24), ('4', 0)], default='3', max_length=1)),
                ('input_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payments', max_digits=100)),
                ('output_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Invoice Cost', max_digits=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
            options={
                'verbose_name_plural': '9. Προμηθευτές',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VendorPaycheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('date_expired', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('paid_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.PaymentMethod')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_paychecks', to='catalogue.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Τίτλος Κατηγορίας')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': '3. Κατηγορίες Αποθήκης',
                'verbose_name_plural': '3. Κατηγορίες Αποθήκης',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.WarehouseCategory', verbose_name='Warehouse Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_site',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.ProductClass'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='catalogue.Product', verbose_name='Related Products'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Vendor'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='product_related',
            field=models.ManyToManyField(related_name='product_related', to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='products_gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='attributeproductclass',
            name='product_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attr_class', to='catalogue.Product', verbose_name='Προϊόν'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='class_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_attributes', to='catalogue.AttributeProductClass'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalogue.AttributeTitle'),
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristics',
            unique_together={('product_related', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetitle',
            unique_together={('title', 'attri_by')},
        ),
    ]
