# Generated by Django 2.0.7 on 2019-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
