# Generated by Django 2.1.7 on 2019-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190318_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclass',
            options={'verbose_name': 'Product Class', 'verbose_name_plural': 'Product Classes'},
        ),
        migrations.AddField(
            model_name='warehousecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False, verbose_name='Is Offer'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Picture'),
        ),
    ]
