# Generated by Django 2.0.7 on 2019-03-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190319_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristicsvalue',
            options={'ordering': ['custom_ordering']},
        ),
        migrations.AddField(
            model_name='characteristicsvalue',
            name='custom_ordering',
            field=models.IntegerField(default=0, help_text='Bigger is better', verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='characteristicsvalue',
            name='char_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='char_details', to='catalogue.Characteristics'),
        ),
    ]
