# Generated by Django 2.0.7 on 2019-03-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190319_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristics',
            old_name='costum_ordering',
            new_name='custom_ordering',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='costum_ordering',
            new_name='custom_ordering',
        ),
        migrations.RemoveField(
            model_name='characteristicsvalue',
            name='costum_ordering',
        ),
    ]
