# Generated by Django 2.0.7 on 2019-03-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20190319_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('have_transcations', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attributetitle',
            options={'ordering': ['ordering_by', '-title']},
        ),
        migrations.AlterModelOptions(
            name='characteristicsvalue',
            options={'ordering': ['-custom_ordering', 'title']},
        ),
        migrations.AddField(
            model_name='attributetitle',
            name='attri_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.AttributeClass'),
        ),
    ]
