# Generated by Django 2.0.7 on 2019-03-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20190320_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetitle',
            options={'ordering': ['ordering_by', 'title']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty_kilo',
            new_name='qty_measure',
        ),
        migrations.AlterField(
            model_name='attributetitle',
            name='attri_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_values', to='catalogue.AttributeClass'),
        ),
        migrations.AlterField(
            model_name='characteristicsvalue',
            name='char_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_values', to='catalogue.Characteristics'),
        ),
    ]
