# Generated by Django 2.0.7 on 2019-03-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190322_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='class_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_attributes', to='catalogue.AttributeProductClass'),
        ),
    ]
