# Generated by Django 2.0 on 2019-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190324_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='characteristicsvalue',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(blank=True, choices=[('1', 'Τεμάχια'), ('2', 'Κιλά'), ('3', 'Κιβώτια')], default='1', max_length=1, null=True, verbose_name='Measute unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order oode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_discount',
            field=models.IntegerField(default=0, verbose_name="'Discount on Order"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='First Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price Buy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_measure',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Pieces per Pack'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='catalogue.Product', verbose_name='Related Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='safe_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Stock Limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
