# Generated by Django 2.0.7 on 2019-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190329_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributetitle',
            options={'ordering': ['-ordering_by', 'title']},
        ),
        migrations.AlterField(
            model_name='attributetitle',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='attributetitle',
            unique_together={('title', 'attri_by')},
        ),
    ]
