# Generated by Django 2.0.7 on 2019-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_featured_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attributeproductclass',
            unique_together=set(),
        ),
    ]
