# Generated by Django 2.0.7 on 2019-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190411_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_add',
            field=models.DecimalField(decimal_places=2, default=0, help_text='System use it only if warehouse transations', max_digits=10, verbose_name='Qty Add'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_remove',
            field=models.DecimalField(decimal_places=2, default=0, help_text='System use it only if warehouse transations', max_digits=10, verbose_name='Qty Remove'),
        ),
    ]
