# Generated by Django 2.0 on 2019-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20190416_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaycheck',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
