# Generated by Django 2.0.7 on 2019-04-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_vendorpaycheck_paid_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='remaining_deposit',
        ),
        migrations.AddField(
            model_name='vendor',
            name='input_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payments', max_digits=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='output_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Invoice Cost', max_digits=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='vendorpaycheck',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_paychecks', to='catalogue.Vendor'),
        ),
    ]
