# Generated by Django 2.0.7 on 2019-04-02 12:14

from django.db import migrations, models
import django.db.models.manager
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=200)),

            ],
            managers=[
                ('browser', django.db.models.manager.Manager()),
            ],
        ),
    ]
