# Generated by Django 2.1.7 on 2019-03-18 12:18

from django.db import migrations, models
import django.db.models.deletion
import site_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Τίτλος')),
                ('site_active', models.BooleanField(default=False, verbose_name='Εμφάνιση στο site')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιπλέον Κόστος')),
                ('limit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Όριο')),
                ('first_choice', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Τρόποι Πληρωμής',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Τίτλος')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Κόστος')),
                ('limit_value', models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Όριο')),
                ('first_choice', models.BooleanField(default=False, verbose_name='Πρώτη Επιλόγη')),
                ('ordering_by', models.IntegerField(default=1, verbose_name='Σειρα Προτεριότητας')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Country')),
            ],
            options={
                'verbose_name_plural': 'Τρόποι Μεταφοράς',
                'ordering': ['-ordering_by'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Κατάστημα',
            },
        ),
    ]
