# Generated by Django 2.0 on 2019-04-17 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import site_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=site_settings.models.upload_banner, validators=[site_settings.models.validate_size])),
            ],
            managers=[
                ('browser', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('payment_type', models.CharField(choices=[('a', 'Cash'), ('b', 'Bank'), ('c', 'Credit Card'), ('d', 'Internet Service')], default='a', max_length=1)),
                ('site_active', models.BooleanField(default=False, verbose_name='Show on FrontEnd')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping additional Cost')),
                ('limit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost Limit')),
                ('first_choice', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Τρόποι Πληρωμής',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Cost')),
                ('limit_value', models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Limit')),
                ('first_choice', models.BooleanField(default=False, verbose_name='First Choice')),
                ('ordering_by', models.IntegerField(default=1, verbose_name='Priority Order')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_settings.Country')),
            ],
            options={
                'verbose_name_plural': 'Τρόποι Μεταφοράς',
                'ordering': ['-ordering_by'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Κατάστημα',
            },
        ),
    ]
