# Generated by Django 2.0.7 on 2019-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('a', 'Cash'), ('b', 'Bank'), ('c', 'Credit Card'), ('d', 'Internet Service')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping additional Cost'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='limit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost Limit'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='site_active',
            field=models.BooleanField(default=False, verbose_name='Show on FrontEnd'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
