# Generated by Django 2.0.7 on 2019-03-26 12:36

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20190325_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='first_choice',
            field=models.BooleanField(default=False, verbose_name='First Choice'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='limit_value',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, validators=[site_settings.models.validate_positive_decimal], verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='ordering_by',
            field=models.IntegerField(default=1, verbose_name='Priority Order'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
