# Generated by Django 2.0.7 on 2019-04-02 12:42

from django.db import migrations, models
import django.db.models.manager
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20190326_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(height_field=1200, upload_to=site_settings.models.upload_banner, validators=[site_settings.models.validate_size], width_field=1500)),
            ],
            managers=[
                ('browser', django.db.models.manager.Manager()),
            ],
        ),
    ]
