# Generated by Django 2.0.7 on 2019-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(height_field=1200, upload_to='', width_field=1500),
        ),
    ]
