# Generated by Django 2.0.7 on 2019-04-02 13:11

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20190402_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=site_settings.models.upload_banner, validators=[site_settings.models.validate_size]),
        ),
    ]
