# Generated by Django 2.0.7 on 2019-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_session',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='date_created',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
