# Generated by Django 2.0.7 on 2019-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190411_1537'),
        ('cart', '0003_auto_20190409_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='cartattribute',
            name='attributes',
            field=models.ManyToManyField(to='catalogue.Attribute'),
        ),
    ]
